name: Get latest release version
on:
  schedule:
    - cron:  '53 5 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        id: fetch
        run: |
          curl -sL https://api.github.com/repos/open-telemetry/opentelemetry-go/releases/latest | \
          jq -r ".tag_name" > tools/opentelemetry-go-latest.txt
          echo ::set-output name=version::$(cat tools/opentelemetry-go-latest.txt)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          for pkg in `grep go.opentelemetry.io/otel go.mod  | awk '{print $1}'`; do go get $pkg@${{ steps.fetch.outputs.version }}"; done
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update opentelemetry-go ${{ steps.fetch.outputs.version }}
          title: Update SwaggerUI to ${{ steps.fetch.outputs.version }}
          body: |
            Updates [opentelemetry-go][1] to ${{ steps.fetch.outputs.version }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/open-telemetry/opentelemetry-go
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: swagger-ui-updates